version: '3'

services: 
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Pass1234
      - MYSQL_DATABASE=team6
  app:
    image: maven:3.5
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Pass1234
      - DATABASE_NAME=team6  
      - DATABASE_PORT=3306
    volumes:
      - ".:/app"
    working_dir: /app
    command: bash -c "mvn spring-boot:run"
