version: '3'

services: 
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=springboot
  app:
    image: maven:3.5
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Pass1234
      - DATABASE_NAME=springboot  
      - DATABASE_PORT=3306
    volumes:
      - ".:/app"
    working_dir: /app
    command: bash -c "mvn package && java -jar target/team6-0.1.0.jar"
